openapi: "3.0.0"
info:
  description: "Métodos disponibles API GoodWayPilgrim"
  version: "1.0.0"
  title: "API GoodWayPilgrim"
paths:
  /auth/register:
    post:
      summary: "Add a new user"
      parameters:
        - name: user
          in: query
          schema:
            type: object
            properties:
              name:
                type: string
                description: User name
                example: "Irene"
              surname:
                type: string
                description: User surname
                example: "Sánchez"
              email:
                type: string
                description: User email
                example: "irene@example.com"
              password:
                type: string
                description: User password
                example: "123123"
      responses:
        "200":
          description: "New user created"
          content:
            application/json:
              schema:
                type: string
                example: "ok"

        "405":
          description: "Invalid input"
          content:
            application/json:
              schema:
                type: string
                example: "not ok"
## YAML Template.
---
